

import type {Metadata} from "next";
import "./globals.css";
import Navbar from "@/components/layout/navbar";
import Sidebar from "@/components/layout/sidebar";


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {

	return (
		<html lang="pt-BR">
			<body>
				<Navbar/>
				<Sidebar />
				<main className="z-20 overflow-hidden">{children}</main>
				<footer></footer>
			</body>
		</html>
	);
}
